services:
   trino-coordinator:
      image: trinodb/trino
      container_name: trino-coordinator
      ports:
         - "8080:8080"
      volumes:
         - ./trino/coordinator/etc:/etc/trino
      networks:
         - data-network

   trino-worker-1:
      image: trinodb/trino
      container_name: trino-worker-1
      volumes:
         - ./trino/worker-1/etc:/etc/trino
      depends_on:
        - trino-coordinator
      networks:
         - data-network

   trino-worker-2:
      image: trinodb/trino
      container_name: trino-worker-2
      volumes:
         - ./trino/worker-2/etc:/etc/trino
      depends_on:
        - trino-coordinator
      networks:
         - data-network

networks:
   data-networks:
      external: true