
name: 'transformer'
version: '1.0.0'
profile: 'transformer'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  transformer:
    staging:
      +schema: staging
      +materialized: table
    marts:
      +schema: marts
      +materialized: table
    reports:
      +schema: reports
      +materialized: table 
