transformer:
   target: dev
   outputs:
      dev:
         type: trino
         method: none
         user: dbt
         host: localhost
         port: 8080
         database: iceberg
         schema: dbt
         threads: 4